# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_emicion', models.DateField(blank=True, null=True)),
                ('fecha_actividad', models.DateField(blank=True, null=True)),
                ('hora_actividad', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ActividadesColegio',
                'verbose_name': 'ActividadColegio',
            },
        ),
        migrations.CreateModel(
            name='ActividadEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_emicion', models.DateField(blank=True, null=True)),
                ('fecha_actividad', models.DateField(blank=True, null=True)),
                ('hora_activdad', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ActividadesEscolares',
                'verbose_name': 'ActividadEscolar',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'verbose_name': 'Alumno',
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Apoderados',
                'verbose_name': 'Apoderado',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('asiste', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'verbose_name': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'CargasAcademicas',
                'verbose_name': 'CargaAcademica',
            },
        ),
        migrations.CreateModel(
            name='CargoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'CargosEscolares',
                'verbose_name': 'CargoEscolar',
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('departamento', models.CharField(blank=True, max_length=60, null=True)),
                ('provincia', models.CharField(blank=True, max_length=60, null=True)),
                ('distrito', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_1', models.IntegerField(blank=True, null=True)),
                ('telefono_2', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Colegios',
                'verbose_name': 'Colegio',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'verbose_name': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
                'verbose_name': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=60, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('sexo', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, help_text='ejemplo@email.com', max_length=254, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='/imagenes')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('ubicacion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Salones',
                'verbose_name': 'Salon',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Docente'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Curso'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Salon'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Curso'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cargaAcademica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.CargaAcademica'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cargoEscolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.CargoEscolar'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Colegio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Persona'),
        ),
        migrations.AddField(
            model_name='actividadescolar',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Salon'),
        ),
    ]
