# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='telefono_1',
        ),
        migrations.RemoveField(
            model_name='colegio',
            name='telefono_2',
        ),
    ]
