# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20161104_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='descripcion',
            field=models.TextField(default='true'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colegio',
            name='distrito',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='provincia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='telefono_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='telefono_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
