# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20161104_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cargaAcademica',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cargaAcademica',
            field=models.ManyToManyField(to='registro.CargaAcademica'),
        ),
    ]
