from .alumno import *
from .persona import *
from .docente import *
from .apoderado import *
from .salon import *
from .asistencia import *
from .actividadColegio import *
from .actividadEscolar import *
from .cargoEscolar import *
from .cargaAcademica import *
from .curso import *
from .colegio import *
